version: "3.3"
services:
  database:
    image: elestio/postgres:15
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: ${SOFTWARE_PASSWORD}
      POSTGRES_DB: "directus"
  cache:
    image: redis:6
    restart: always
    networks:
      - directus
  directus:
    restart: always
    image: elestio/directus:${SOFTWARE_VERSION_TAG}
    ports:
      - 172.17.0.1:8055:8055
    user: 0:0
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: ${SOFTWARE_PASSWORD}
      SECRET: ${SOFTWARE_PASSWORD}
      PUBLIC_URL: https://${DOMAIN}
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: ${SOFTWARE_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_TRANSPORT: "smtp"
      EMAIL_SMTP_HOST: "172.17.0.1"
      EMAIL_SMTP_PORT: 25
      EMAIL_SMTP_SECURE: "false"
      EMAIL_SMTP_IGNORE_TLS: "true"
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      CACHE_REDIS: "redis://cache:6379"
      REDIS: "redis://cache:6379"
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CACHE_AUTO_PURGE: "true"
      NODE_TLS_REJECT_UNAUTHORIZED: 0
networks:
  directus:
